package greenely.greenely.retail.ui.events

enum class ClickEvents {
    RETAIL_START_PROMOCODE_TOP_BUTTON_CLICK,
    RETAIL_START_PROMOCODE_BOTTOM_BUTTON_CLICK,
    RETAIL_START_TOP_CONTINUE_CLICK,
    RETAIL_START_BOTTOM_CONTINUE_CLICK,
    COMING_SOON_PROMOCODE_TOP_BUTTON_CLICK,
    COMING_SOON_PROMOCODE_BOTTOM_BUTTON_CLICK,
    COMING_SOON_TOP_INTERESTED_CLICK,
    COMING_SOON_BOTTOM_INTERESTED_CLICK,
}